version: '3.9'

services:
  postgres:
    container_name: submission.postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=submission
  dictionary-manager_mongo:
    container_name: submission.dictionary-manager.db
    image: bitnami/mongodb:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: dictionary-manager
      MONGODB_ROOT_PASSWORD: password123
  dictionary-manager_service:
    container_name: submission.dictionary-manager.service
    image: ghcr.io/pan-canadian-genome-library/dictionary-manager:edge
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: dictionary-manager_mongo
      MONGO_PORT: 27017
      MONGO_DB: dictionary-manager
      MONGO_USER: admin
      MONGO_PASS: password
volumes:
  mongodb_data:
    name: dictionary-manager-mongo-data
    driver: local
