components:
  parameters:
    path:
      CategoryId:
        name: categoryId
        in: path
        required: true
        schema:
          type: string
        description: ID of the category to which the data belongs
      DacId:
        name: dacId
        in: path
        required: true
        schema:
          type: string
        description: ID of the DAC user
      EntityName:
        description: The name of the Entity
        name: entityName
        in: path
        schema:
          type: string
        required: true
      FieldName:
        description: The name of the Field
        name: fieldName
        in: path
        schema:
          type: string
        required: true
      Organization:
        name: organization
        in: path
        required: true
        schema:
          type: string
        description: Organization name
      StudyId:
        name: studyId
        description: The Unique identifier of the study in PCGL.
    query:
      OnlyActive:
        description: Optional query parameter to filter results to include only active submissions. Default value is false
        name: onlyActive
        in: query
        schema:
          type: boolean
        required: false
      Organization:
        description: The name of the Organization
        name: organization
        in: query
        schema:
          type: string
        required: true
      OrganizationFilter:
        description: Optional query parameter to filter results to include only submissions associated to an specific organization. By default, returns submissions from all organizations
        name: organization
        in: query
        schema:
          type: string
        required: false
      OrderBy:
        name: orderBy
        in: query
        required: false
        schema:
          type: string
          enum: ['asc', 'desc']
          default: 'asc'
        description: Optional query parameter to specify the order direction based on created date. Default value is asc.
      Page:
        name: page
        in: query
        required: false
        schema:
          type: integer
        description: Optional query parameter to specify the page number of the results. Default value is 1
      PageSize:
        name: pageSize
        in: query
        required: false
        schema:
          type: integer
        description: Optional query parameter to specify the number of results per page. Default value is 20
      Study:
        description: Study ID to check
        name: study
        in: query
        schema:
          type: string
        required: true
      Value:
        name: value
        in: query
        required: true
        schema:
          type: string
        description: The value to search for in the specified field
      View:
        name: view
        in: query
        required: false
        schema:
          type: string
          enum: ['flat', 'compound']
        description: Optional query parameter to define the data format. Choose 'flat' for a simple, single-level collection of records, or 'compound' for a nested, schema-centric structure. The default value is 'flat'
